without retrieve secret action

diff --git a/.github/workflows/git-secret-docker.yaml b/.github/workflows/git-secret-docker.yaml
--- a/.github/workflows/git-secret-docker.yaml
+++ b/.github/workflows/git-secret-docker.yaml
@@ -27,9 +27,39 @@ jobs:
             password: ${{ secrets.GITHUB_TOKEN }}
 
         steps:
+          # - name: Retrieve secret
+          #   id: retrieve-secret
+          #   uses: SAG-Trial/QM/.github/actions/RetrieveSecrets@main
+
           - name: Retrieve secret
             id: retrieve-secret
-            uses: SAG-Trial/QM/.github/actions/RetrieveSecrets@main
+            run: |
+              #!/bin/bash
+
+              # Check if the INPUT environment variable is set
+              if [ -n "$INPUT" ]; then
+                  # Check if INPUT equals "weather"
+                  if [ "$INPUT" = "weather" ]; then
+                      # Send the content of .env to GITHUB_OUTPUT
+                      if [ -f "/secrets/.env" ]; then
+                          CONTENT=$(cat /secrets/.env | grep "^WEATHER_API=" | awk -F '=' '{print $2}'
+                          )
+                          echo "WEATHER_API_KEY=$CONTENT" >> $GITHUB_OUTPUT
+                      else
+                          echo "Error: .env file not found"
+                          exit 1
+                      fi
+                  else
+                      echo "Error: INPUT is not set to 'weather'"
+                      exit 1
+                  fi
+              else
+                  echo "Error: INPUT environment variable not set"
+                  exit 1
+              fi
+
+              # If everything is successful, exit with a success code (0)
+              exit 0
 
     verifying-output:
       runs-on: ubuntu-latest
