tree and finding uniqueness

diff --git a/.github/workflows/git-secret-docker.yaml b/.github/workflows/git-secret-docker.yaml
--- a/.github/workflows/git-secret-docker.yaml
+++ b/.github/workflows/git-secret-docker.yaml
@@ -31,47 +31,55 @@ jobs:
           #   id: retrieve-secret
           #   uses: SAG-Trial/QM/.github/actions/RetrieveSecrets@main
 
-          - name: Retrieve secret
-            id: retrieve-secret
-            run: |
-              #!/bin/bash
+          # - name: Retrieve secret
+          #   id: retrieve-secret
+          #   run: |
+          #     #!/bin/bash
 
-              # Check if the INPUT environment variable is set
-              if [ -n "$INPUT" ]; then
-                  # Check if INPUT equals "weather"
-                  if [ "$INPUT" = "weather" ]; then
-                      # Send the content of .env to GITHUB_OUTPUT
-                      if [ -f "/secrets/.env" ]; then
-                          CONTENT=$(cat /secrets/.env | grep "^WEATHER_API=" | awk -F '=' '{print $2}'
-                          )
-                          echo "WEATHER_API_KEY=$CONTENT" >> $GITHUB_OUTPUT
-                      else
-                          echo "Error: .env file not found"
-                          exit 1
-                      fi
-                  else
-                      echo "Error: INPUT is not set to 'weather'"
-                      exit 1
-                  fi
-              else
-                  echo "Error: INPUT environment variable not set"
-                  exit 1
-              fi
+          #     # Check if the INPUT environment variable is set
+          #     if [ -n "$INPUT" ]; then
+          #         # Check if INPUT equals "weather"
+          #         if [ "$INPUT" = "weather" ]; then
+          #             # Send the content of .env to GITHUB_OUTPUT
+          #             if [ -f "/secrets/.env" ]; then
+          #                 CONTENT=$(cat /secrets/.env | grep "^WEATHER_API=" | awk -F '=' '{print $2}'
+          #                 )
+          #                 echo "WEATHER_API_KEY=$CONTENT" >> $GITHUB_OUTPUT
+          #             else
+          #                 echo "Error: .env file not found"
+          #                 exit 1
+          #             fi
+          #         else
+          #             echo "Error: INPUT is not set to 'weather'"
+          #             exit 1
+          #         fi
+          #     else
+          #         echo "Error: INPUT environment variable not set"
+          #         exit 1
+          #     fi
 
-              # If everything is successful, exit with a success code (0)
-              exit 0
+          #     # If everything is successful, exit with a success code (0)
+          #     exit 0
 
-    verifying-output:
-      runs-on: ubuntu-latest
-      needs: secret-image-container-job
-      steps:
-        - name: Display the output
-          run: echo ${{needs.secret-image-container-job.outputs.WEATHER_API_KEY}}
+          - name: Check Home Directory
+            run: echo $HOME
+            
+          - name: List / contents
+            run: | 
+              cd /
+              tree
 
-        - name: Get Weather
-          uses: SAG-Trial/QM/.github/actions/GetWeather@main
-          env:
-              PASSWORD: ${{ needs.secret-image-container-job.outputs.WEATHER_API_KEY }}
+    # verifying-output:
+    #   runs-on: ubuntu-latest
+    #   needs: secret-image-container-job
+    #   steps:
+    #     - name: Display the output
+    #       run: echo ${{needs.secret-image-container-job.outputs.WEATHER_API_KEY}}
+
+    #     - name: Get Weather
+    #       uses: SAG-Trial/QM/.github/actions/GetWeather@main
+    #       env:
+    #           PASSWORD: ${{ needs.secret-image-container-job.outputs.WEATHER_API_KEY }}
 
         
     # get-ouput-from-container-job:
